filenames_PC = {'links':'./Data_Files/links.csv',
                'nodes':'./Data_Files/nodes.csv',
                'raw_data':'../../travel_times_2011.csv',
                'data_coo_form':'../../data_coo_form.txt',
                'data_trips':'../../data_trips.csv',
                'data_traveltimes':'../../data_travel_times.csv',
                'full_link_ids':'./Data_Files/full_link_ids.csv',
                'full_link_trips':'./Data_Files/full_link_trips.json',
                'full_link_traveltimes':'./Data_Files/full_link_travel_times.json',
                'nanlink1':'./Data_Files/Nanlink1.json',
                'W':'./Data_Files/W.txt',
                'random':'./Data_Files/Random_numbers.txt'}

filenames_cluster = {'links':'./scratch/links.csv',
                     'nodes':'./scratch/nodes.csv',
                     'raw_data':'./scratch/travel_times_2011.csv',
                     'data_coo_form':'./scratch/data_coo_form.txt',
                     'data_trips':'./scratch/data_trips.csv',
                     'data_traveltimes':'./scratch/data_travel_times.csv',
                     'full_link_ids':'./scratch/full_link_ids.csv',
                     'full_link_trips':'./scratch/full_link_trips.json',
                     'full_link_traveltimes':'./scratch/full_link_travel_times.json',
                     'W':'./scratch/W.txt',
                     'random':'./scratch/Random_numbers.txt'}
